#!/bin/bash

# Always check custom bin PATH set first. If not exit.
if ! echo "$PATH" | grep -q "$HOME/.local/bin"; then
    echo "0"
    exit 1
fi

case "$1" in
    "-s")
        cp comsui "$HOME/.local/bin/"
        chmod +x $HOME/.local/bin/comsui
        echo "Synced comsui to ~/.local/bin"
        ;;
    "-p")
        cp "$HOME/.local/bin/comsui" ./
        echo "Pulled comsui from ~/.local/bin"
        ;;
    *)
        echo "Usage: $0 {s|p}"
        echo "  s - Sync comsui to ~/.local/bin for from repo editing"
        echo "  p - Pull comsui from ~/.local/bin for live editing"
        ;;
esac
