#!/bin/bash
# Check for options
# Import libraries and show location info
ext_desc=""
c_desc=""
# ID + Date + Count per repository
randid=$(s_random 6 A-Z0-9)
today=$(t_date)
repo_name=$(g_repo)
user_id=$(n_user)
count_f="/tmp/${APP}_${repo_name}_${today}_${user_id}"