#!/bin/bash
BIN_PATH="/.local/bin"
# Always check custom bin PATH set first. If not exit.
if d_ex "${HOME}${BIN_PATH}/"; then
    info "Found local bin."
else 
    die "Local bin not available"
fi

if ! s_inpath "${HOME}${BIN_PATH}"; then
    die "Bin not in path"
fi

# Only run sync if argument matches
case "$*" in
    *-t*|*-f*|*-p*|*-d*)
    case "$1" in
        "-p")
            info $PATH && exit
            ;;
        "-t")
            # Remove existing app files if they exist
            f_remove "$(p_bin)"
            rm -rf "$(p_binlib)"

            # Copy executable directly to bin
            cp "${APP:-comsui}" "$(p_bin)"
            f_exec "$(p_bin)"

            # Create app-lib directory and copy all lib files
            d_make "$(p_binlib)"
            cp lib/* "$(p_binlib)/"

            info "Synced $APP to ~$BIN_PATH"
            shift
            ;;
        "-f")
            cp "$(p_bin)" ./"$APP"
            cp "$(p_binlib)/"* lib/
            info "Pulled $APP from ~$BIN_PATH"
            shift  
            exit 0
            ;;
        "-d")
            f_remove "$(p_bin)" 
            rm -rf "${HOME}${BIN_PATH}/${APP}-lib/"
            info "Deleted $APP from ~$BIN_PATH"
            shift  
            exit 0
    esac
        ;;
    *)
        info "Skipped sync"
        ;;
esac
